---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-promus
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      monit: clickhouse
  template:
    metadata:
      labels:
        monit: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: "/etc/clickhouse-server"
          name: main-config
      - name: clickhouse-exporter
        image: f1yegor/clickhouse-exporter
        args:
        - "-scrape_uri=http://localhost:8123"
        ports:
        - containerPort: 9116
        volumeMounts:
        - mountPath: "/etc/clickhouse-server"
          name: main-config
        
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-promus
  labels:
    app: clickhouse
spec:
  selector:
    monit: clickhouse
  ports:
  - protocol: TCP
    port: 8123
    targetPort: 8123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-promus
  labels:
    app: clickhouse
data:
  config.xml: |


