---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-promus
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      monit: grafana
  template:
    metadata:
      labels:
        monit: grafana
    spec:
      initContainers:
      - name: prep-grafana
        image: busybox:latest
        command: ['sh', '-c', 'chmod o+rwx -R /var/lib/grafana']
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-dir 
      nodeName: k8s-master
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /var/lib/grafana-promus
          type: DirectoryOrCreate
        name: grafana-dir
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-dir 
      nodeName: k8s-master
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /var/lib/grafana-promus
          type: DirectoryOrCreate
        name: grafana-dir
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-promus
  labels:
    app: grafana
spec:
  selector:
    monit: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
