#!/bin/bash
IFNAME=$(lshw -class network 2>/dev/null|grep -C 1 -P \("bus info"\|"сведения о шине"\)|grep -P \(name\|имя\)|awk -F': ' '{print $2}')
if [ ${EUID:--1} = "0" ];then
  echo "creating hap-net for haproxy container..."
  docker network create -d macvlan --subnet=192.168.176.0/24 --ip-range=192.168.176.5/32 --gateway=192.168.176.2 -o parent=$IFNAME hap-net
  docker network ls -f name=hap-net
else
  echo "You need run this script as root"
fi
