apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "k8s-lb:6443"
etcd:
  external:
    endpoints:
    - http://k8s-master:2379
    - http://node2:2379
    - http://node3:2379
